const ROUTE_ACCOUNT = '/account';
export const ROUTE_ACCOUNT_HOME = `${ROUTE_ACCOUNT}/`;
export const ROUTE_ACCOUNT_PERSONAL_INFO = `${ROUTE_ACCOUNT}/personal-info`;
export const ROUTE_ACCOUNT_MY_PLANS = `${ROUTE_ACCOUNT}/my-plans`;

export const ROUTES = {
  HOME: ROUTE_ACCOUNT_HOME,
  PERSONAL_INFO: ROUTE_ACCOUNT_PERSONAL_INFO,
  MY_PLANS: ROUTE_ACCOUNT_MY_PLANS,
};

const ACCOUNTS_BASE_PATH = '/v1/Users';
export const ENDPOINT_ACCOUNTS_BY_ID = `${ACCOUNTS_BASE_PATH}/:id`;
export const ENDPOINT_UPDATE_ACCOUNT_PASSWORD = `${ACCOUNTS_BASE_PATH}/:id/changepassword`;

export const ENDPOINTS = {
  GET_BY_ID: ENDPOINT_ACCOUNTS_BY_ID,
  EDIT: ENDPOINT_ACCOUNTS_BY_ID,
  UPDATE_PASSWORD: ENDPOINT_UPDATE_ACCOUNT_PASSWORD,
};
