const ROUTE_AUTH = '/auth';
export const ROUTE_AUTH_LOGIN = `${ROUTE_AUTH}/login`;
export const ROUTE_AUTH_FORGOT_PASSWORD = `${ROUTE_AUTH}/forgot-password`;
export const ROUTE_AUTH_RESET_SENT = `${ROUTE_AUTH}/reset-sent`;
export const ROUTE_AUTH_SUPPORT = `${ROUTE_AUTH}/support`;
export const ROUTE_AUTH_HELP_CENTER = `${ROUTE_AUTH}/help-center`;
export const ROUTE_AUTH_ADMIN_ACCESS = `${ROUTE_AUTH}/admin`;

export const ROUTES = {
  LOGIN: ROUTE_AUTH_LOGIN,
  FORGOT_PASSWORD: ROUTE_AUTH_FORGOT_PASSWORD,
  RESET_SENT: ROUTE_AUTH_RESET_SENT,
  SUPPORT: ROUTE_AUTH_SUPPORT,
  HELP_CENTER: ROUTE_AUTH_HELP_CENTER,
  ADMIN_ACCESS: ROUTE_AUTH_ADMIN_ACCESS,
};

const USERS_BASE_PATH = '/v1/Users';
export const ENDPOINT_LIST_USERS = `${USERS_BASE_PATH}/`;
export const ENDPOINT_CREATE_USER = `${USERS_BASE_PATH}/`;
export const ENDPOINT_GET_USER_BY_ID = `${USERS_BASE_PATH}/:id`;
export const ENDPOINT_EDIT_USER_BY_ID = `${USERS_BASE_PATH}/:id`;
export const ENDPOINT_AUTHENTICATE = `${USERS_BASE_PATH}/authenticate`;
export const ENDPOINT_CHANGE_PASSWORD_BY_ID = `${USERS_BASE_PATH}/:id/changepassword`;
export const ENDPOINT_RECOVER_PASSWORD = `${USERS_BASE_PATH}/recoverpassword`;
export const ENDPOINT_REFRESH_TOKEN = `${USERS_BASE_PATH}/refreshtoken`;

export const ENDPOINTS = {
  LIST_USERS: ENDPOINT_LIST_USERS,
  CREATE_USER: ENDPOINT_CREATE_USER,
  GET_USER_BY_ID: ENDPOINT_GET_USER_BY_ID,
  EDIT_USER_BY_ID: ENDPOINT_EDIT_USER_BY_ID,
  AUTHENTICATE: ENDPOINT_AUTHENTICATE,
  CHANGE_PASSWORD_BY_ID: ENDPOINT_CHANGE_PASSWORD_BY_ID,
  RECOVER_PASSWORD: ENDPOINT_RECOVER_PASSWORD,
  REFRESH_TOKEN: ENDPOINT_REFRESH_TOKEN,
};

export const PUBLIC_ENDPOINT_LIST = [
  ENDPOINT_AUTHENTICATE,
  ENDPOINT_RECOVER_PASSWORD,
  ENDPOINT_REFRESH_TOKEN,
];

export const AUTH_SESSION_KEY = 'auth:brain:session';
