import { ValueMap } from '../../utils/typings';
import { ValidHealthImpactSubjects } from './types';

const ROUTE_ANALYSIS = '/analysis';
export const ROUTE_ANALYSIS_HOME = `${ROUTE_ANALYSIS}/`;
export const ROUTE_ANALYSIS_CREATE = `${ROUTE_ANALYSIS}/create`;
export const ROUTE_ANALYSIS_CREATE_CORESET = `${ROUTE_ANALYSIS_CREATE}/core-set`;
export const ROUTE_ANALYSIS_CORESET_PATIENT = `${ROUTE_ANALYSIS_CREATE_CORESET}/patient`;
export const ROUTE_ANALYSIS_CORESET_FORM_CATEGORIES = `${ROUTE_ANALYSIS_CREATE_CORESET}/form-configuration`;
export const ROUTE_ANALYSIS_CORESET_FORM_FILLING = `${ROUTE_ANALYSIS_CREATE_CORESET}/form-filling`;
export const ROUTE_ANALYSIS_CORESET_FINISH = `${ROUTE_ANALYSIS_CREATE_CORESET}/finish`;
export const ROUTE_ANALYSIS_CREATE_PROSPECTIVE_RESULT_MAP = `${ROUTE_ANALYSIS_CREATE}/prospective-result-map`;
export const ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_PATIENT = `${ROUTE_ANALYSIS_CREATE_PROSPECTIVE_RESULT_MAP}/patient`;
export const ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_MAP = `${ROUTE_ANALYSIS_CREATE_PROSPECTIVE_RESULT_MAP}/map`;
export const ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_FINISH = `${ROUTE_ANALYSIS_CREATE_PROSPECTIVE_RESULT_MAP}/finish`;
export const ROUTE_ANALYSIS_CREATE_GLOBAL_PROGNOSTIC = `${ROUTE_ANALYSIS_CREATE}/global-prognostic`;
export const ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_PATIENT = `${ROUTE_ANALYSIS_CREATE_GLOBAL_PROGNOSTIC}/patient`;
export const ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_WEAKNESS_AND_STRENGTHS = `${ROUTE_ANALYSIS_CREATE_GLOBAL_PROGNOSTIC}/weakness-and-strengths`;
export const ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_FINISH = `${ROUTE_ANALYSIS_CREATE_GLOBAL_PROGNOSTIC}/finish`;
export const ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE = `${ROUTE_ANALYSIS_CREATE}/neuropsichological-profile`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_PATIENT = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/patient`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_INTELECTUAL_OPERATION = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/intelectual-operation`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/universal-functions`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_MEMORY = `${ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS}/memory`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_ATTENTION = `${ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS}/attention`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_EXECUTIVE_FUNCTIONS = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/executive-functions`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_COGNITIVE_FUNCTIONS = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/cognitive-functions`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_ADDITIONAL_INFO = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/additional-information`;
export const ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_FINISH = `${ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE}/finish`;
export const ROUTE_ANALYSIS_CREATE_HEALTH_IMPACT = `${ROUTE_ANALYSIS_CREATE}/health-impact`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_PATIENT = `${ROUTE_ANALYSIS_CREATE_HEALTH_IMPACT}/patient`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS = `${ROUTE_ANALYSIS_CREATE_HEALTH_IMPACT}/subjects`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_PICK = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/pick`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_COPING = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/coping`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_ANXIETY = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/anxiety`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_HUMOUR = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/humour`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_LIFE_QUALITY = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/life-quality`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_SLEEP_QUALITY = `${ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS}/sleep-quality`;
export const ROUTE_ANALYSIS_HEALTH_IMPACT_FINISH = `${ROUTE_ANALYSIS_CREATE_HEALTH_IMPACT}/finish`;
export const ROUTE_ANALYSIS_REPORT = `${ROUTE_ANALYSIS}/reports/:patientId`;
export const ROUTE_ANALYSIS_REPORT_CORESET = `${ROUTE_ANALYSIS_REPORT}/coreset/:coreSetId/diagnostic/:id`;
export const ROUTE_ANALYSIS_REPORT_GLOBAL_PROGNOSTIC = `${ROUTE_ANALYSIS_REPORT}/global-prognostic/:coreSetId/diagnostic/:id`;
export const ROUTE_ANALYSIS_REPORT_PROSPECTIVE_RESULT_MAP = `${ROUTE_ANALYSIS_REPORT}/prospective-result-map/:coreSetId/diagnostic/:id`;
export const ROUTE_ANALYSIS_REPORT_NEUROPSICHOLOGICAL_PROFILE = `${ROUTE_ANALYSIS_REPORT}/neuropsichological-profile/:id`;

export const ROUTES = {
  HOME: ROUTE_ANALYSIS_HOME,
  CREATE: ROUTE_ANALYSIS_CREATE,
  CREATE_CORESET: ROUTE_ANALYSIS_CREATE_CORESET,
  CORESET_PATIENT: ROUTE_ANALYSIS_CORESET_PATIENT,
  CORESET_FORM_CATEGORIES: ROUTE_ANALYSIS_CORESET_FORM_CATEGORIES,
  CORESET_FORM_FILLING: ROUTE_ANALYSIS_CORESET_FORM_FILLING,
  CORESET_FINISH: ROUTE_ANALYSIS_CORESET_FINISH,
  CREATE_PROSPECTIVE_RESULT_MAP: ROUTE_ANALYSIS_CREATE_PROSPECTIVE_RESULT_MAP,
  PROSPECTIVE_RESULT_MAP_PATIENT: ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_PATIENT,
  PROSPECTIVE_RESULT_MAP_MAP: ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_MAP,
  PROSPECTIVE_RESULT_MAP_FINISH: ROUTE_ANALYSIS_PROSPECTIVE_RESULT_MAP_FINISH,
  CREATE_GLOBAL_PROGNOSTIC: ROUTE_ANALYSIS_CREATE_GLOBAL_PROGNOSTIC,
  GLOBAL_PROGNOSTIC_PATIENT: ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_PATIENT,
  GLOBAL_PROGNOSTIC_WEAKNESS_AND_STRENGTHS: ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_WEAKNESS_AND_STRENGTHS,
  GLOBAL_PROGNOSTIC_FINISH: ROUTE_ANALYSIS_GLOBAL_PROGNOSTIC_FINISH,
  CREATE_NEUROPSICHOLOGICAL_PROFILE: ROUTE_ANALYSIS_CREATE_NEUROPSICHOLOGICAL_PROFILE,
  NEUROPSICHOLOGICAL_PROFILE_PATIENT: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_PATIENT,
  NEUROPSICHOLOGICAL_PROFILE_INTELECTUAL_OPERATION: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_INTELECTUAL_OPERATION,
  NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS,
  NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_MEMORY: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_MEMORY,
  NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_ATTENTION: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_UNIVERSAL_FUNCTIONS_ATTENTION,
  NEUROPSICHOLOGICAL_PROFILE_EXECUTIVE_FUNCTIONS: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_EXECUTIVE_FUNCTIONS,
  NEUROPSICHOLOGICAL_PROFILE_COGNITIVE_FUNCTIONS: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_COGNITIVE_FUNCTIONS,
  NEUROPSICHOLOGICAL_PROFILE_ADDITIONAL_INFO: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_ADDITIONAL_INFO,
  NEUROPSICHOLOGICAL_PROFILE_FINISH: ROUTE_ANALYSIS_NEUROPSICHOLOGICAL_PROFILE_FINISH,
  CREATE_HEALTH_IMPACT: ROUTE_ANALYSIS_CREATE_HEALTH_IMPACT,
  HEALTH_IMPACT_PATIENT: ROUTE_ANALYSIS_HEALTH_IMPACT_PATIENT,
  HEALTH_IMPACT_SUBJECTS: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS,
  HEALTH_IMPACT_SUBJECTS_PICK: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_PICK,
  HEALTH_IMPACT_SUBJECTS_COPING: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_COPING,
  HEALTH_IMPACT_SUBJECTS_ANXIETY: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_ANXIETY,
  HEALTH_IMPACT_SUBJECTS_HUMOUR: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_HUMOUR,
  HEALTH_IMPACT_SUBJECTS_LIFE_QUALITY: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_LIFE_QUALITY,
  HEALTH_IMPACT_SUBJECTS_SLEEP_QUALITY: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_SLEEP_QUALITY,
  HEALTH_IMPACT_FINISH: ROUTE_ANALYSIS_HEALTH_IMPACT_FINISH,
  REPORT_CORESET: ROUTE_ANALYSIS_REPORT_CORESET,
  REPORT_GLOBAL_PROGNOSTIC: ROUTE_ANALYSIS_REPORT_GLOBAL_PROGNOSTIC,
  REPORT_PROSPECTIVE_RESULT_MAP: ROUTE_ANALYSIS_REPORT_PROSPECTIVE_RESULT_MAP,
  REPORT_NEUROPSICHOLOGICAL_PROFILE: ROUTE_ANALYSIS_REPORT_NEUROPSICHOLOGICAL_PROFILE,
};

const CORESETS_BASE_PATH = '/v1/CoreSets';
export const ENDPOINT_LIST_CORESETS = `${CORESETS_BASE_PATH}/`;
export const ENDPOINT_GET_CORESET_BY_ID = `${CORESETS_BASE_PATH}/:id`;

const RESEARCH_FORMS_BASE_PATH = '/v1/ResearchForms';
export const ENDPOINT_LIST_RESEARCH_FORMS = `${RESEARCH_FORMS_BASE_PATH}/`;
export const ENDPOINT_GET_RESEARCH_FORM_BY_ID = `${RESEARCH_FORMS_BASE_PATH}/:id`;

export const ENDPOINTS = {
  LIST_CORESETS: ENDPOINT_LIST_CORESETS,
  GET_CORESET_BY_ID: ENDPOINT_GET_CORESET_BY_ID,
  LIST_RESEARCH_FORMS: ENDPOINT_LIST_RESEARCH_FORMS,
  GET_RESEARCH_FORM_BY_ID: ENDPOINT_GET_RESEARCH_FORM_BY_ID,
};

export const PAGINATION_CORESETS_PER_PAGE = 10;
export const HEALTH_IMPACT_FORM_SUBJECTS = [
  'coping',
  'anxiety',
  'humour',
  'lifeQuality',
  'sleepQuality',
];

export const HEALTH_IMPACT_FORM_ROUTES_ORDER = {
  coping: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_COPING,
  anxiety: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_ANXIETY,
  humour: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_HUMOUR,
  lifeQuality: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_LIFE_QUALITY,
  sleepQuality: ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_SLEEP_QUALITY,
};

export function getNextFormRoute(
  selectedSubjects: ValidHealthImpactSubjects[],
  currentRoute: string
) {
  const enabledRoutes = Object.entries(HEALTH_IMPACT_FORM_ROUTES_ORDER)
    .filter(([key]) =>
      selectedSubjects.includes(key as ValidHealthImpactSubjects)
    )
    .map((pair) => pair[1]);

  if (currentRoute === ROUTE_ANALYSIS_HEALTH_IMPACT_SUBJECTS_PICK) {
    return enabledRoutes[0];
  }

  const currentRouteIndex = enabledRoutes.indexOf(currentRoute);

  return (
    enabledRoutes[currentRouteIndex + 1] || ROUTE_ANALYSIS_HEALTH_IMPACT_FINISH
  );
}

export function getPreviousFormRoute(
  selectedSubjects: ValidHealthImpactSubjects[],
  currentRoute: string
) {
  const enabledRoutes = Object.entries(HEALTH_IMPACT_FORM_ROUTES_ORDER)
    .filter(([key]) =>
      selectedSubjects.includes(key as ValidHealthImpactSubjects)
    )
    .map((pair) => pair[1]);

  if (currentRoute === ROUTE_ANALYSIS_HEALTH_IMPACT_FINISH) {
    return enabledRoutes[enabledRoutes.length - 1];
  }

  const currentRouteIndex = enabledRoutes.indexOf(currentRoute);

  return (
    enabledRoutes[currentRouteIndex - 1] || ROUTE_ANALYSIS_HEALTH_IMPACT_FINISH
  );
}

export enum DocumentTypes {
  'CoreSet' = 'CoreSet',
  'GlobalPrognostic' = 'GlobalPrognostic',
  'ProspectiveResultMap' = 'ProspectiveResultMap',
  'NeuropsichologicalProfile' = 'NeuropsichologicalProfile',
}

export enum VerbModes {
  'Edit' = 'edit',
  'Create' = 'create',
}

export const totalQualifiersMap: ValueMap<number> = {
  'FUNÇÕES DO CORPO': 4,
  'ESTRUTURAS DO CORPO': 7,
  'ATIVIDADES E PARTICIPAÇÃO': 4,
  'FATORES AMBIENTAIS': 8,
};

export const defaultQualifierMap = {
  0: 0,
  1: 1,
  2: 2,
  3: 3,
  4: 4,
  8: 5,
  9: 6,
};

export const valueQualifiersMap: ValueMap<ValueMap<number>> = {
  'FUNÇÕES DO CORPO': defaultQualifierMap,
  'ESTRUTURAS DO CORPO': {
    ...defaultQualifierMap,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
  },
  'ATIVIDADES E PARTICIPAÇÃO': defaultQualifierMap,
  'FATORES AMBIENTAIS': {
    ...defaultQualifierMap,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
  },
};

const DEFAULT_CATEGORY_TICKS = ['0', '1', '2', '3', '4'];

export const CATEGORY_TICK_MAP: ValueMap<string[]> = {
  'FUNÇÕES DO CORPO': DEFAULT_CATEGORY_TICKS,
  'ESTRUTURAS DO CORPO': ['0', '1', '2', '3', '4', '5', '6', '7'],
  'ATIVIDADES E PARTICIPAÇÃO': DEFAULT_CATEGORY_TICKS,
  'FATORES AMBIENTAIS': ['-4', '-3', '-2', '-1', '0', '+1', '+2', '+3', '+4'],
};

export const ENVIRONMENTAL_FACTORS_QUALIFIER_MAP: Record<number, string> = {
  0: '4',
  1: '3',
  2: '2',
  3: '1',
  4: '0',
  5: '+1',
  6: '+2',
  7: '+3',
  8: '+4',
  9: '8',
  10: '9',
};

export const ENVIRONMENTAL_FACTORS_REPORT_MAP: Record<number, number> = {
  0: -4,
  1: -3,
  2: -2,
  3: -1,
  4: 0,
  5: 1,
  6: 2,
  7: 3,
  8: 4,
  9: 8,
  10: 9,
};
